### ISSUE TITLE
451 Status Code

### ISSUE THREAD

**Issue by rjtmahinay** [quarkusio/quarkus-http#135]
Is it possible in this time to add a 451 status code? here's my scenario.

**Scenario:**

As a consultant that create an application for a legal system, we may want to submit a status code of 451 for API calls that isn't allowed at this time due to a governance policy/restriction. For a better status code, I'm proposing this one.

I'm seeing that a 401 Unauthorized doesn't seem right for my use-case. Let me know for any suggestion.

NOTE: Seeing that this is supported in Spring Framework, existing Legal-based APIs that want to migrate to Quarkus could have a breaking change or will use another **inappropriate code** for this use-case.

**Comment by stuartwdouglas** [comment]
Do you mean adding it to here: https://github.com/quarkusio/quarkus-http/blob/main/http-core/src/main/java/io/undertow/httpcore/StatusCodes.java#L88

If so just open a pull request. 

Note that you can already return 451, the status code API just takes an integer.

**Comment by rjtmahinay** [comment]
@stuartwdouglas Thanks, will open a pull request for this. Appreciate your consideration in my use-case 😄
