### ISSUE TITLE
Ability to set MAX_PARAMETERS in Undertow

### ISSUE THREAD

**Issue by benkard** [quarkusio/quarkus-http#63]
When using Undertow, a request with more than 1,000 parameters triggers a `io.undertow.util.ParameterLimitException`.  While that's a reasonable default, I have a need to configure it.  (A JSF application I am porting to Quarkus via the MyFaces Quarkus extension generates very large requests.)

Undertow provides a way of providing it with an `UndertowOptionMap`, one key of which is `MAX_PARAMETERS`.  It would be nice if there were a way of setting it through `application.properties`.

**Comment by stuartwdouglas** [comment]
https://github.com/quarkusio/quarkus-http/commit/00223f28f17a246a3075b3f1ce38dc289976a641

Once this is released it will need some code to wire it up in Quarkus

**Comment by benkard** [comment]
Wow, that was super fast.  Thank you!

**Comment by benkard** [comment]
Here's a start on the Quarkus side: https://github.com/quarkusio/quarkus/commit/12dde7db9b7c06992bd1c6f8a57b5dda379d5596

Still need to add a test or two before I open a PR.
