### ISSUE TITLE
`getUserPrincipal` is not implemented on VertxWebSocketHttpExchange

### ISSUE THREAD

**Issue by aldoborrero** [quarkusio/quarkus-http#84]
Related to the discussion we are having on [OIDC authentication for websockets doesn't work in 1.13.*
](https://github.com/quarkusio/quarkus/issues/16602), `getUserPrincipal` is not yet implemented which is a useful functionality. This is the comment I left originally there:

Playing around with the code, inside `VertxWebSocketHttpExchange` we do have access to the original `RoutingContext` in the class attribute `exchange`.

![image](https://user-images.githubusercontent.com/82811/133102173-3b635134-78ca-432e-bf24-6bef95c14f1c.png)

Upon closer inspection, I can see the `principal` is correctly populated inside the `exchange.data()` map like we can see below:

![image](https://user-images.githubusercontent.com/82811/133102574-7364aced-a981-4c36-bc2a-b6ce3f9c5c97.png)

Is it safe to assume that we can return directly that object in method `getUserPrincipal`? Or is there any other implication I'm not taking into account (which will be probably)?

Something like:

![image](https://user-images.githubusercontent.com/82811/133235841-9943e9cd-0884-490b-98b6-7055d8d632c2.png)

If needed I can prepare the PR with proper guidance.

**Comment by cescoffier** [comment]
Fixed by #83
